server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3301/mcln"
    username: root
    password: 08112001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
application:
    security:
        api-key: "bb92a925-c464-4376-9a27-bd54e40f9caf"
        
file:
    upload-path: "E:/MCLN/Data"
